#! /usr/bin/env bash

if [ -z "${1}" ]; then
  print "No instruction provided"
fi

if [ "${1}" == "docker-build" ]; then
  docker build -t so-2020-2-gcc .
  exit 0
fi

if [ "${1}" == "compile" ]; then
  docker run --rm -v $PWD:/app -w /app so-2020-2-gcc make
  exit 0
fi

if [ "${1}" == "run" ]; then
  docker run --rm -v $PWD:/app -w /app so-2020-2-gcc make check
  exit 0
fi

if [ "${1}" == "test" ]; then
  docker run --rm -v $PWD:/app -w /app so-2020-2-gcc make check
  exit 0
fi

if [ "${1}" == "clean" ]; then
  docker run --rm -v $PWD:/app -w /app so-2020-2-gcc make clean
  exit 0
fi

docker run --rm -v $PWD:/app -w /app so-2020-2-gcc ${1}
